# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/controlplane/metricsreader/mrpb/v1/metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4src/controlplane/metricsreader/mrpb/v1/metrics.proto\x12*gml.internal.controlplane.metricsreader.v1\"<\n\x0cMetricSample\x12\x14\n\x05times\x18\x01 \x03(\x03R\x05times\x12\x16\n\x06values\x18\x02 \x03(\x01R\x06values\"J\n\x0fHistogramSample\x12\x1f\n\x0b\x62ucket_ends\x18\x01 \x03(\x01R\nbucketEnds\x12\x16\n\x06\x63ounts\x18\x02 \x03(\x01R\x06\x63ounts\"\x92\x03\n\nMetricData\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12Z\n\x06labels\x18\x02 \x03(\x0b\x32\x42.gml.internal.controlplane.metricsreader.v1.MetricData.LabelsEntryR\x06labels\x12_\n\rmetric_sample\x18\x03 \x01(\x0b\x32\x38.gml.internal.controlplane.metricsreader.v1.MetricSampleH\x00R\x0cmetricSample\x12h\n\x10histogram_sample\x18\x04 \x01(\x0b\x32;.gml.internal.controlplane.metricsreader.v1.HistogramSampleH\x00R\x0fhistogramSample\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x0e\n\x0csample_oneof\"f\n\x12RangeQueryResponse\x12P\n\x07results\x18\x01 \x03(\x0b\x32\x36.gml.internal.controlplane.metricsreader.v1.MetricDataR\x07results\"\x83\x01\n\x11RangeQueryRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n\x08relative\x18\x02 \x01(\tR\x08relative\x12\x14\n\x05start\x18\x03 \x01(\tR\x05start\x12\x12\n\x04stop\x18\x04 \x01(\tR\x04stop\x12\x12\n\x04step\x18\x05 \x01(\tR\x04step2\xa4\x01\n\x14MetricsReaderService\x12\x8b\x01\n\nRangeQuery\x12=.gml.internal.controlplane.metricsreader.v1.RangeQueryRequest\x1a>.gml.internal.controlplane.metricsreader.v1.RangeQueryResponseBBZ@gimletlabs.ai/gimlet/src/controlplane/metricsreader/mrpb/v1;mrpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.controlplane.metricsreader.mrpb.v1.metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z@gimletlabs.ai/gimlet/src/controlplane/metricsreader/mrpb/v1;mrpb'
  _METRICDATA_LABELSENTRY._options = None
  _METRICDATA_LABELSENTRY._serialized_options = b'8\001'
  _METRICSAMPLE._serialized_start=100
  _METRICSAMPLE._serialized_end=160
  _HISTOGRAMSAMPLE._serialized_start=162
  _HISTOGRAMSAMPLE._serialized_end=236
  _METRICDATA._serialized_start=239
  _METRICDATA._serialized_end=641
  _METRICDATA_LABELSENTRY._serialized_start=568
  _METRICDATA_LABELSENTRY._serialized_end=625
  _RANGEQUERYRESPONSE._serialized_start=643
  _RANGEQUERYRESPONSE._serialized_end=745
  _RANGEQUERYREQUEST._serialized_start=748
  _RANGEQUERYREQUEST._serialized_end=879
  _METRICSREADERSERVICE._serialized_start=882
  _METRICSREADERSERVICE._serialized_end=1046
# @@protoc_insertion_point(module_scope)
